
package gnf.moma.gendocumentfiles;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GenDocumentumFilesService", targetNamespace = "http://www.gasnaturalfenosa.com/MOMA/GenDocumentumFiles", wsdlLocation = "http://wom.intranet.gasnatural.com/momaservicesnnr/GenDocumentumFilesService?wsdl")
public class GenDocumentumFilesService
    extends Service
{

    private final static URL GENDOCUMENTUMFILESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(gnf.moma.gendocumentfiles.GenDocumentumFilesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = gnf.moma.gendocumentfiles.GenDocumentumFilesService.class.getResource(".");
            url = new URL(baseUrl, "http://wom.intranet.gasnatural.com/momaservicesnnr/GenDocumentumFilesService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://wom.intranet.gasnatural.com/momaservicesnnr/GenDocumentumFilesService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GENDOCUMENTUMFILESSERVICE_WSDL_LOCATION = url;
    }

    public GenDocumentumFilesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenDocumentumFilesService() {
        super(GENDOCUMENTUMFILESSERVICE_WSDL_LOCATION, new QName("http://www.gasnaturalfenosa.com/MOMA/GenDocumentumFiles", "GenDocumentumFilesService"));
    }

    /**
     * 
     * @return
     *     returns ServicePortType
     */
    @WebEndpoint(name = "servicePort")
    public ServicePortType getServicePort() {
        return super.getPort(new QName("http://www.gasnaturalfenosa.com/MOMA/GenDocumentumFiles", "servicePort"), ServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePortType
     */
    @WebEndpoint(name = "servicePort")
    public ServicePortType getServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.gasnaturalfenosa.com/MOMA/GenDocumentumFiles", "servicePort"), ServicePortType.class, features);
    }

}
