
package org.tempuri;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.sealsignbssservice.BiometricSignatureBeginResponseBasic;
import org.datacontract.schemas._2004._07.sealsignbsstypes.BiometricSignatureParameters;
import org.datacontract.schemas._2004._07.sealsignbsstypes.BiometricSignatureType;
import org.datacontract.schemas._2004._07.sealsignbsstypes.BiometricSignatureVerification;
import org.datacontract.schemas._2004._07.sealsignbsstypes.BiometricVerificationParameters;
import org.datacontract.schemas._2004._07.sealsigndsstypes.SignatureParameters;
import org.datacontract.schemas._2004._07.sealsigndsstypes.SignatureProfile;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IBiometricSignatureServiceBasic", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    org.tempuri.ObjectFactory.class,
    org.datacontract.schemas._2004._07.sealsignbsstypes.ObjectFactory.class,
    org.datacontract.schemas._2004._07.sealsignbssservice.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.sealsigndsstypes.ObjectFactory.class
})
public interface IBiometricSignatureServiceBasic {


    /**
     * 
     * @throws IBiometricSignatureServiceBasicHeartBeatSealSignDSSFaultContractFaultFaultMessage
     */
    @WebMethod(operationName = "HeartBeat", action = "http://tempuri.org/IBiometricSignatureServiceBasic/HeartBeat")
    @RequestWrapper(localName = "HeartBeat", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HeartBeat")
    @ResponseWrapper(localName = "HeartBeatResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HeartBeatResponse")
    public void heartBeat()
        throws IBiometricSignatureServiceBasicHeartBeatSealSignDSSFaultContractFaultFaultMessage
    ;

    /**
     * 
     * @param biometricOptions
     * @param id
     * @param signatureProfile
     * @param biometricParameters
     * @param biometricSignatureType
     * @param signingDocument
     * @param account
     * @param parameters
     * @param detachedSignature
     * @param options
     * @return
     *     returns org.datacontract.schemas._2004._07.sealsignbssservice.BiometricSignatureBeginResponseBasic
     * @throws IBiometricSignatureServiceBasicBeginSignatureSealSignDSSFaultContractFaultFaultMessage
     */
    @WebMethod(operationName = "BeginSignature", action = "http://tempuri.org/IBiometricSignatureServiceBasic/BeginSignature")
    @WebResult(name = "BeginSignatureResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BeginSignature", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BeginSignature")
    @ResponseWrapper(localName = "BeginSignatureResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BeginSignatureResponse")
    public BiometricSignatureBeginResponseBasic beginSignature(
        @WebParam(name = "signatureProfile", targetNamespace = "http://tempuri.org/")
        SignatureProfile signatureProfile,
        @WebParam(name = "biometricSignatureType", targetNamespace = "http://tempuri.org/")
        BiometricSignatureType biometricSignatureType,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "biometricOptions", targetNamespace = "http://tempuri.org/")
        List<String> biometricOptions,
        @WebParam(name = "biometricParameters", targetNamespace = "http://tempuri.org/")
        BiometricSignatureParameters biometricParameters,
        @WebParam(name = "options", targetNamespace = "http://tempuri.org/")
        List<String> options,
        @WebParam(name = "parameters", targetNamespace = "http://tempuri.org/")
        SignatureParameters parameters,
        @WebParam(name = "detachedSignature", targetNamespace = "http://tempuri.org/")
        byte[] detachedSignature,
        @WebParam(name = "signingDocument", targetNamespace = "http://tempuri.org/")
        byte[] signingDocument)
        throws IBiometricSignatureServiceBasicBeginSignatureSealSignDSSFaultContractFaultFaultMessage
    ;

    /**
     * 
     * @param biometricState
     * @param instance
     * @return
     *     returns byte[]
     * @throws IBiometricSignatureServiceBasicEndSignatureSealSignDSSFaultContractFaultFaultMessage
     */
    @WebMethod(operationName = "EndSignature", action = "http://tempuri.org/IBiometricSignatureServiceBasic/EndSignature")
    @WebResult(name = "EndSignatureResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EndSignature", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EndSignature")
    @ResponseWrapper(localName = "EndSignatureResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EndSignatureResponse")
    public byte[] endSignature(
        @WebParam(name = "instance", targetNamespace = "http://tempuri.org/")
        String instance,
        @WebParam(name = "biometricState", targetNamespace = "http://tempuri.org/")
        byte[] biometricState)
        throws IBiometricSignatureServiceBasicEndSignatureSealSignDSSFaultContractFaultFaultMessage
    ;

    /**
     * 
     * @param biometricOptions
     * @param id
     * @param signatureProfile
     * @param document
     * @param biometricParameters
     * @param biometricState
     * @param biometricSignatureType
     * @param account
     * @param detachedSignature
     * @return
     *     returns org.datacontract.schemas._2004._07.sealsignbsstypes.BiometricSignatureVerification
     * @throws IBiometricSignatureServiceBasicVerifySealSignDSSFaultContractFaultFaultMessage
     */
    @WebMethod(operationName = "Verify", action = "http://tempuri.org/IBiometricSignatureServiceBasic/Verify")
    @WebResult(name = "VerifyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Verify", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Verify")
    @ResponseWrapper(localName = "VerifyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerifyResponse")
    public BiometricSignatureVerification verify(
        @WebParam(name = "signatureProfile", targetNamespace = "http://tempuri.org/")
        SignatureProfile signatureProfile,
        @WebParam(name = "biometricSignatureType", targetNamespace = "http://tempuri.org/")
        BiometricSignatureType biometricSignatureType,
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id,
        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
        String account,
        @WebParam(name = "biometricOptions", targetNamespace = "http://tempuri.org/")
        List<String> biometricOptions,
        @WebParam(name = "biometricParameters", targetNamespace = "http://tempuri.org/")
        BiometricVerificationParameters biometricParameters,
        @WebParam(name = "biometricState", targetNamespace = "http://tempuri.org/")
        byte[] biometricState,
        @WebParam(name = "detachedSignature", targetNamespace = "http://tempuri.org/")
        byte[] detachedSignature,
        @WebParam(name = "document", targetNamespace = "http://tempuri.org/")
        byte[] document)
        throws IBiometricSignatureServiceBasicVerifySealSignDSSFaultContractFaultFaultMessage
    ;

    /**
     * 
     * @param signatureProfile
     * @param document
     * @param biometricState
     * @param instance
     * @return
     *     returns org.datacontract.schemas._2004._07.sealsignbsstypes.BiometricSignatureVerification
     * @throws IBiometricSignatureServiceBasicGetInfoFromBiometricStateSealSignDSSFaultContractFaultFaultMessage
     */
    @WebMethod(operationName = "GetInfoFromBiometricState", action = "http://tempuri.org/IBiometricSignatureServiceBasic/GetInfoFromBiometricState")
    @WebResult(name = "GetInfoFromBiometricStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInfoFromBiometricState", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoFromBiometricState")
    @ResponseWrapper(localName = "GetInfoFromBiometricStateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoFromBiometricStateResponse")
    public BiometricSignatureVerification getInfoFromBiometricState(
        @WebParam(name = "signatureProfile", targetNamespace = "http://tempuri.org/")
        SignatureProfile signatureProfile,
        @WebParam(name = "instance", targetNamespace = "http://tempuri.org/")
        String instance,
        @WebParam(name = "biometricState", targetNamespace = "http://tempuri.org/")
        byte[] biometricState,
        @WebParam(name = "document", targetNamespace = "http://tempuri.org/")
        byte[] document)
        throws IBiometricSignatureServiceBasicGetInfoFromBiometricStateSealSignDSSFaultContractFaultFaultMessage
    ;

    /**
     * 
     * @param signatureProfile
     * @param document
     * @return
     *     returns org.datacontract.schemas._2004._07.sealsignbsstypes.BiometricSignatureVerification
     * @throws IBiometricSignatureServiceBasicGetInfoSealSignDSSFaultContractFaultFaultMessage
     */
    @WebMethod(operationName = "GetInfo", action = "http://tempuri.org/IBiometricSignatureServiceBasic/GetInfo")
    @WebResult(name = "GetInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfo")
    @ResponseWrapper(localName = "GetInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoResponse")
    public BiometricSignatureVerification getInfo(
        @WebParam(name = "signatureProfile", targetNamespace = "http://tempuri.org/")
        SignatureProfile signatureProfile,
        @WebParam(name = "document", targetNamespace = "http://tempuri.org/")
        byte[] document)
        throws IBiometricSignatureServiceBasicGetInfoSealSignDSSFaultContractFaultFaultMessage
    ;

    /**
     * 
     * @param biometricOptions
     * @param id
     * @param signatureProfile
     * @param offlineBiometricState
     * @param biometricParameters
     * @param biometricSignatureType
     * @param signingDocument
     * @param account
     * @param parameters
     * @param instance
     * @param detachedSignature
     * @param options
     * @return
     *     returns byte[]
     * @throws IBiometricSignatureServiceBasicSyncOfflineSignatureSealSignDSSFaultContractFaultFaultMessage
     */
//    @WebMethod(operationName = "SyncOfflineSignature", action = "http://tempuri.org/IBiometricSignatureServiceBasic/SyncOfflineSignature")
//    @WebResult(name = "SyncOfflineSignatureResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "SyncOfflineSignature", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncOfflineSignature")
//    @ResponseWrapper(localName = "SyncOfflineSignatureResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncOfflineSignatureResponse")
//    public byte[] syncOfflineSignature(
//        @WebParam(name = "signatureProfile", targetNamespace = "http://tempuri.org/")
//        SignatureProfile signatureProfile,
//        @WebParam(name = "biometricSignatureType", targetNamespace = "http://tempuri.org/")
//        BiometricSignatureType biometricSignatureType,
//        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
//        String id,
//        @WebParam(name = "account", targetNamespace = "http://tempuri.org/")
//        String account,
//        @WebParam(name = "biometricOptions", targetNamespace = "http://tempuri.org/")
//        List<String> biometricOptions,
//        @WebParam(name = "biometricParameters", targetNamespace = "http://tempuri.org/")
//        BiometricSignatureParameters biometricParameters,
//        @WebParam(name = "options", targetNamespace = "http://tempuri.org/")
//        List<String> options,
//        @WebParam(name = "parameters", targetNamespace = "http://tempuri.org/")
//        SignatureParameters parameters,
//        @WebParam(name = "detachedSignature", targetNamespace = "http://tempuri.org/")
//        byte[] detachedSignature,
//        @WebParam(name = "signingDocument", targetNamespace = "http://tempuri.org/")
//        byte[] signingDocument,
//        @WebParam(name = "instance", targetNamespace = "http://tempuri.org/")
//        String instance,
//        @WebParam(name = "offlineBiometricState", targetNamespace = "http://tempuri.org/")
//        byte[] offlineBiometricState)
//        throws IBiometricSignatureServiceBasicSyncOfflineSignatureSealSignDSSFaultContractFaultFaultMessage
//    ;

    /**
     * 
     * @param offlineSignatures
     * @param signatureProfile
     * @param signingDocument
     * @param detachedSignature
     * @return
     *     returns byte[]
     * @throws IBiometricSignatureServiceBasicSyncOfflineSignaturesSealSignDSSFaultContractFaultFaultMessage
     */
//    @WebMethod(operationName = "SyncOfflineSignatures", action = "http://tempuri.org/IBiometricSignatureServiceBasic/SyncOfflineSignatures")
//    @WebResult(name = "SyncOfflineSignaturesResult", targetNamespace = "http://tempuri.org/")
//    @RequestWrapper(localName = "SyncOfflineSignatures", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncOfflineSignatures")
//    @ResponseWrapper(localName = "SyncOfflineSignaturesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SyncOfflineSignaturesResponse")
//    public byte[] syncOfflineSignatures(
//        @WebParam(name = "signatureProfile", targetNamespace = "http://tempuri.org/")
//        SignatureProfile signatureProfile,
//        @WebParam(name = "offlineSignatures", targetNamespace = "http://tempuri.org/")
//        ArrayOfOfflineBiometricSignature offlineSignatures,
//        @WebParam(name = "detachedSignature", targetNamespace = "http://tempuri.org/")
//        byte[] detachedSignature,
//        @WebParam(name = "signingDocument", targetNamespace = "http://tempuri.org/")
//        byte[] signingDocument)
//        throws IBiometricSignatureServiceBasicSyncOfflineSignaturesSealSignDSSFaultContractFaultFaultMessage
//    ;

}
