package gnf.momacon.momaconportal.ofsc.servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import gnf.momacon.momaconportal.toa.activity.dto.ActionActivityParameters;
import gnf.momacon.momaconportal.toa.activity.dto.ActivityResponse;
import gnf.momacon.momaconportal.toa.activity.dto.CreateActivityParameters;
import gnf.momacon.momaconportal.toa.activity.dto.DelayActivityParameters;
import gnf.momacon.momaconportal.toa.activity.dto.GetActivitiesParameters;
import gnf.momacon.momaconportal.toa.activity.dto.GetActivitiesResponse;
import gnf.momacon.momaconportal.toa.activity.dto.GetActivityLinksParameters;
import gnf.momacon.momaconportal.toa.activity.dto.GetActivityLinksResponseElement;
import gnf.momacon.momaconportal.toa.activity.dto.GetActivityParameters;
import gnf.momacon.momaconportal.toa.activity.dto.GetActivityWorkSkillsParameters;
import gnf.momacon.momaconportal.toa.activity.dto.GetActivityWorkSkillsResponse;
import gnf.momacon.momaconportal.toa.activity.dto.GetFileParameters;
import gnf.momacon.momaconportal.toa.activity.dto.GetFileResponseElement;
import gnf.momacon.momaconportal.toa.activity.dto.GetRequiredInventoriesParameters;
import gnf.momacon.momaconportal.toa.activity.dto.GetRequiredInventoriesResponse;
import gnf.momacon.momaconportal.toa.activity.dto.GetResourcePreferencesParameters;
import gnf.momacon.momaconportal.toa.activity.dto.GetResourcePreferencesResponse;
import gnf.momacon.momaconportal.toa.activity.dto.GetRouteParameters;
import gnf.momacon.momaconportal.toa.activity.dto.LinkActivitiesParameters;
import gnf.momacon.momaconportal.toa.activity.dto.SearchActivitiesParameters;
import gnf.momacon.momaconportal.toa.activity.dto.SetFileParameters;
import gnf.momacon.momaconportal.toa.activity.dto.SetRequiredInventoriesParameters;
import gnf.momacon.momaconportal.toa.activity.dto.SetResourcePreferencesParameters;
import gnf.momacon.momaconportal.toa.activity.dto.SimpleResponse;
import gnf.momacon.momaconportal.toa.activity.dto.StartRouteParameters;
import gnf.momacon.momaconportal.toa.activity.dto.UnlinkActivitiesParameters;
import gnf.momacon.momaconportal.toa.activity.dto.UpdateActivityParameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ApiPortType", targetNamespace = "urn:toa:activity")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ApiPortType {


    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "create_activity", action = "activity/create_activity")
    @WebResult(name = "create_activity_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse createActivity(
        @WebParam(name = "create_activity", targetNamespace = "urn:toa:activity", partName = "body")
        CreateActivityParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "update_activity", action = "activity/update_activity")
    @WebResult(name = "update_activity_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse updateActivity(
        @WebParam(name = "update_activity", targetNamespace = "urn:toa:activity", partName = "body")
        UpdateActivityParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "reopen_activity", action = "activity/reopen_activity")
    @WebResult(name = "reopen_activity_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse reopenActivity(
        @WebParam(name = "reopen_activity", targetNamespace = "urn:toa:activity", partName = "body")
        UpdateActivityParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "start_activity", action = "activity/start_activity")
    @WebResult(name = "start_activity_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse startActivity(
        @WebParam(name = "start_activity", targetNamespace = "urn:toa:activity", partName = "body")
        ActionActivityParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "complete_activity", action = "activity/complete_activity")
    @WebResult(name = "complete_activity_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse completeActivity(
        @WebParam(name = "complete_activity", targetNamespace = "urn:toa:activity", partName = "body")
        ActionActivityParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "suspend_activity", action = "activity/suspend_activity")
    @WebResult(name = "suspend_activity_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse suspendActivity(
        @WebParam(name = "suspend_activity", targetNamespace = "urn:toa:activity", partName = "body")
        ActionActivityParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "cancel_activity", action = "activity/cancel_activity")
    @WebResult(name = "cancel_activity_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse cancelActivity(
        @WebParam(name = "cancel_activity", targetNamespace = "urn:toa:activity", partName = "body")
        ActionActivityParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "prework_activity", action = "activity/prework_activity")
    @WebResult(name = "prework_activity_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse preworkActivity(
        @WebParam(name = "prework_activity", targetNamespace = "urn:toa:activity", partName = "body")
        ActionActivityParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "delay_activity", action = "activity/delay_activity")
    @WebResult(name = "delay_activity_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse delayActivity(
        @WebParam(name = "delay_activity", targetNamespace = "urn:toa:activity", partName = "body")
        DelayActivityParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "get_activity", action = "activity/get_activity")
    @WebResult(name = "get_activity_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse getActivity(
        @WebParam(name = "get_activity", targetNamespace = "urn:toa:activity", partName = "body")
        GetActivityParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "search_activities", action = "activity/search_activities")
    @WebResult(name = "search_activities_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse searchActivities(
        @WebParam(name = "search_activities", targetNamespace = "urn:toa:activity", partName = "body")
        SearchActivitiesParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.ActivityResponse
     */
    @WebMethod(operationName = "get_route", action = "activity/get_route")
    @WebResult(name = "get_route_response", targetNamespace = "urn:toa:activity", partName = "body")
    public ActivityResponse getRoute(
        @WebParam(name = "get_route", targetNamespace = "urn:toa:activity", partName = "body")
        GetRouteParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.SimpleResponse
     */
    @WebMethod(operationName = "start_route", action = "activity/start_route")
    @WebResult(name = "start_route_response", targetNamespace = "urn:toa:activity", partName = "body")
    public SimpleResponse startRoute(
        @WebParam(name = "start_route", targetNamespace = "urn:toa:activity", partName = "body")
        StartRouteParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.SimpleResponse
     */
    @WebMethod(operationName = "end_route", action = "activity/end_route")
    @WebResult(name = "end_route_response", targetNamespace = "urn:toa:activity", partName = "body")
    public SimpleResponse endRoute(
        @WebParam(name = "end_route", targetNamespace = "urn:toa:activity", partName = "body")
        StartRouteParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.SimpleResponse
     */
    @WebMethod(operationName = "link_activities", action = "activity/link_activities")
    @WebResult(name = "link_activities_response", targetNamespace = "urn:toa:activity", partName = "body")
    public SimpleResponse linkActivities(
        @WebParam(name = "link_activities", targetNamespace = "urn:toa:activity", partName = "body")
        LinkActivitiesParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.SimpleResponse
     */
    @WebMethod(operationName = "unlink_activities", action = "activity/unlink_activities")
    @WebResult(name = "unlink_activities_response", targetNamespace = "urn:toa:activity", partName = "body")
    public SimpleResponse unlinkActivities(
        @WebParam(name = "unlink_activities", targetNamespace = "urn:toa:activity", partName = "body")
        UnlinkActivitiesParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.GetActivityLinksResponseElement
     */
    @WebMethod(operationName = "get_activity_links", action = "activity/get_activity_links")
    @WebResult(name = "get_activity_links_response", targetNamespace = "urn:toa:activity", partName = "body")
    public GetActivityLinksResponseElement getActivityLinks(
        @WebParam(name = "get_activity_links", targetNamespace = "urn:toa:activity", partName = "body")
        GetActivityLinksParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.SimpleResponse
     */
    @WebMethod(operationName = "set_file", action = "activity/set_file")
    @WebResult(name = "set_file_response", targetNamespace = "urn:toa:activity", partName = "body")
    public SimpleResponse setFile(
        @WebParam(name = "set_file", targetNamespace = "urn:toa:activity", partName = "body")
        SetFileParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.GetFileResponseElement
     */
    @WebMethod(operationName = "get_file", action = "activity/get_file")
    @WebResult(name = "get_file_response", targetNamespace = "urn:toa:activity", partName = "body")
    public GetFileResponseElement getFile(
        @WebParam(name = "get_file", targetNamespace = "urn:toa:activity", partName = "body")
        GetFileParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.SimpleResponse
     */
    @WebMethod(operationName = "delete_file", action = "activity/delete_file")
    @WebResult(name = "delete_file_response", targetNamespace = "urn:toa:activity", partName = "body")
    public SimpleResponse deleteFile(
        @WebParam(name = "delete_file", targetNamespace = "urn:toa:activity", partName = "body")
        GetFileParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.SimpleResponse
     */
    @WebMethod(operationName = "set_resource_preferences", action = "activity/set_resource_preferences")
    @WebResult(name = "set_resource_preferences_response", targetNamespace = "urn:toa:activity", partName = "body")
    public SimpleResponse setResourcePreferences(
        @WebParam(name = "set_resource_preferences", targetNamespace = "urn:toa:activity", partName = "body")
        SetResourcePreferencesParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.GetResourcePreferencesResponse
     */
    @WebMethod(operationName = "get_resource_preferences", action = "activity/get_resource_preferences")
    @WebResult(name = "get_resource_preferences_response", targetNamespace = "urn:toa:activity", partName = "body")
    public GetResourcePreferencesResponse getResourcePreferences(
        @WebParam(name = "get_resource_preferences", targetNamespace = "urn:toa:activity", partName = "body")
        GetResourcePreferencesParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.SimpleResponse
     */
    @WebMethod(operationName = "set_required_inventories", action = "activity/set_required_inventories")
    @WebResult(name = "set_required_inventories_response", targetNamespace = "urn:toa:activity", partName = "body")
    public SimpleResponse setRequiredInventories(
        @WebParam(name = "set_required_inventories", targetNamespace = "urn:toa:activity", partName = "body")
        SetRequiredInventoriesParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.GetRequiredInventoriesResponse
     */
    @WebMethod(operationName = "get_required_inventories", action = "activity/get_required_inventories")
    @WebResult(name = "get_required_inventories_response", targetNamespace = "urn:toa:activity", partName = "body")
    public GetRequiredInventoriesResponse getRequiredInventories(
        @WebParam(name = "get_required_inventories", targetNamespace = "urn:toa:activity", partName = "body")
        GetRequiredInventoriesParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.GetActivityWorkSkillsResponse
     */
    @WebMethod(operationName = "get_activity_work_skills", action = "activity/get_activity_work_skills")
    @WebResult(name = "get_activity_work_skills_response", targetNamespace = "urn:toa:activity", partName = "body")
    public GetActivityWorkSkillsResponse getActivityWorkSkills(
        @WebParam(name = "get_activity_work_skills", targetNamespace = "urn:toa:activity", partName = "body")
        GetActivityWorkSkillsParameters body);

    /**
     * 
     * @param body
     * @return
     *     returns toa.activity.GetActivitiesResponse
     */
    @WebMethod(operationName = "get_activities", action = "activity/get_activities")
    @WebResult(name = "get_activities_response", targetNamespace = "urn:toa:activity", partName = "body")
    public GetActivitiesResponse getActivities(
        @WebParam(name = "get_activities", targetNamespace = "urn:toa:activity", partName = "body")
        GetActivitiesParameters body);

}
