
package gnf.momacon.momaconportal.ofsc.servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import gnf.momacon.momaconportal.ofsc.dto.DeleteUserElement;
import gnf.momacon.momaconportal.ofsc.dto.GetLocationsElement;
import gnf.momacon.momaconportal.ofsc.dto.GetLocationsResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourceElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourceResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourcesCalendarsElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourcesCalendarsResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourcesListElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourcesListResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourcesLocationsElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourcesLocationsResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourcesSkillsElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourcesSkillsResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourcesZonesElement;
import gnf.momacon.momaconportal.ofsc.dto.GetResourcesZonesResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.GetUserElement;
import gnf.momacon.momaconportal.ofsc.dto.GetUserResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.GetUsersListElement;
import gnf.momacon.momaconportal.ofsc.dto.GetUsersListResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.InsertResourceElement;
import gnf.momacon.momaconportal.ofsc.dto.InsertUserElement;
import gnf.momacon.momaconportal.ofsc.dto.ObjectFactory;
import gnf.momacon.momaconportal.ofsc.dto.SetLocationsElement;
import gnf.momacon.momaconportal.ofsc.dto.SetLocationsResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.SetResourceResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.SetResourcesCalendarsElement;
import gnf.momacon.momaconportal.ofsc.dto.SetResourcesCalendarsResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.SetResourcesLocationsElement;
import gnf.momacon.momaconportal.ofsc.dto.SetResourcesLocationsResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.SetResourcesSkillsElement;
import gnf.momacon.momaconportal.ofsc.dto.SetResourcesSkillsResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.SetResourcesZonesElement;
import gnf.momacon.momaconportal.ofsc.dto.SetResourcesZonesResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.SetUserResponseElement;
import gnf.momacon.momaconportal.ofsc.dto.UpdateResourceElement;
import gnf.momacon.momaconportal.ofsc.dto.UpdateUserElement;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ResourceManagementPort", targetNamespace = "urn:toatech:ResourceManagement:1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ResourceManagementPort {


    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetUserResponseElement
     */
    @WebMethod(operationName = "insert_user", action = "ResourceManagementService/insert_user")
    @WebResult(name = "insert_user_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetUserResponseElement insertUser(
        @WebParam(name = "insert_user", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        InsertUserElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetUserResponseElement
     */
    @WebMethod(operationName = "update_user", action = "ResourceManagementService/update_user")
    @WebResult(name = "update_user_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetUserResponseElement updateUser(
        @WebParam(name = "update_user", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        UpdateUserElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetUserResponseElement
     */
    @WebMethod(operationName = "delete_user", action = "ResourceManagementService/delete_user")
    @WebResult(name = "delete_user_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetUserResponseElement deleteUser(
        @WebParam(name = "delete_user", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        DeleteUserElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.GetUserResponseElement
     */
    @WebMethod(operationName = "get_user", action = "ResourceManagementService/get_user")
    @WebResult(name = "get_user_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public GetUserResponseElement getUser(
        @WebParam(name = "get_user", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        GetUserElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.GetUsersListResponseElement
     */
    @WebMethod(operationName = "get_users_list", action = "ResourceManagementService/get_users_list")
    @WebResult(name = "get_users_list_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public GetUsersListResponseElement getUsersList(
        @WebParam(name = "get_users_list", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        GetUsersListElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetResourceResponseElement
     */
    @WebMethod(operationName = "insert_resource", action = "ResourceManagementService/insert_resource")
    @WebResult(name = "insert_resource_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetResourceResponseElement insertResource(
        @WebParam(name = "insert_resource", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        InsertResourceElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetResourceResponseElement
     */
    @WebMethod(operationName = "update_resource", action = "ResourceManagementService/update_resource")
    @WebResult(name = "update_resource_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetResourceResponseElement updateResource(
        @WebParam(name = "update_resource", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        UpdateResourceElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.GetResourceResponseElement
     */
    @WebMethod(operationName = "get_resource", action = "ResourceManagementService/get_resource")
    @WebResult(name = "get_resource_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public GetResourceResponseElement getResource(
        @WebParam(name = "get_resource", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        GetResourceElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.GetResourcesListResponseElement
     */
    @WebMethod(operationName = "get_resources_list", action = "ResourceManagementService/get_resources_list")
    @WebResult(name = "get_resources_list_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public GetResourcesListResponseElement getResourcesList(
        @WebParam(name = "get_resources_list", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        GetResourcesListElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetResourcesCalendarsResponseElement
     */
    @WebMethod(operationName = "set_resources_calendars", action = "ResourceManagementService/set_resources_calendars")
    @WebResult(name = "set_resources_calendars_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetResourcesCalendarsResponseElement setResourcesCalendars(
        @WebParam(name = "set_resources_calendars", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        SetResourcesCalendarsElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.GetResourcesCalendarsResponseElement
     */
    @WebMethod(operationName = "get_resources_calendars", action = "ResourceManagementService/get_resources_calendars")
    @WebResult(name = "get_resources_calendars_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public GetResourcesCalendarsResponseElement getResourcesCalendars(
        @WebParam(name = "get_resources_calendars", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        GetResourcesCalendarsElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetResourcesSkillsResponseElement
     */
    @WebMethod(operationName = "set_resources_skills", action = "ResourceManagementService/set_resources_skills")
    @WebResult(name = "set_resources_skills_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetResourcesSkillsResponseElement setResourcesSkills(
        @WebParam(name = "set_resources_skills", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        SetResourcesSkillsElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.GetResourcesSkillsResponseElement
     */
    @WebMethod(operationName = "get_resources_skills", action = "ResourceManagementService/get_resources_skills")
    @WebResult(name = "get_resources_skills_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public GetResourcesSkillsResponseElement getResourcesSkills(
        @WebParam(name = "get_resources_skills", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        GetResourcesSkillsElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetResourcesZonesResponseElement
     */
    @WebMethod(operationName = "set_resources_zones", action = "ResourceManagementService/set_resources_zones")
    @WebResult(name = "set_resources_zones_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetResourcesZonesResponseElement setResourcesZones(
        @WebParam(name = "set_resources_zones", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        SetResourcesZonesElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.GetResourcesZonesResponseElement
     */
    @WebMethod(operationName = "get_resources_zones", action = "ResourceManagementService/get_resources_zones")
    @WebResult(name = "get_resources_zones_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public GetResourcesZonesResponseElement getResourcesZones(
        @WebParam(name = "get_resources_zones", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        GetResourcesZonesElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetLocationsResponseElement
     */
    @WebMethod(operationName = "update_locations", action = "ResourceManagementService/update_locations")
    @WebResult(name = "update_locations_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetLocationsResponseElement updateLocations(
        @WebParam(name = "update_locations", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        SetLocationsElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetLocationsResponseElement
     */
    @WebMethod(operationName = "delete_locations", action = "ResourceManagementService/delete_locations")
    @WebResult(name = "delete_locations_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetLocationsResponseElement deleteLocations(
        @WebParam(name = "delete_locations", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        SetLocationsElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.GetLocationsResponseElement
     */
    @WebMethod(operationName = "get_locations", action = "ResourceManagementService/get_locations")
    @WebResult(name = "get_locations_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public GetLocationsResponseElement getLocations(
        @WebParam(name = "get_locations", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        GetLocationsElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.SetResourcesLocationsResponseElement
     */
    @WebMethod(operationName = "set_resources_locations", action = "ResourceManagementService/set_resources_locations")
    @WebResult(name = "set_resources_locations_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public SetResourcesLocationsResponseElement setResourcesLocations(
        @WebParam(name = "set_resources_locations", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        SetResourcesLocationsElement params);

    /**
     * 
     * @param params
     * @return
     *     returns toatech.resourcemanagement._1.GetResourcesLocationsResponseElement
     */
    @WebMethod(operationName = "get_resources_locations", action = "ResourceManagementService/get_resources_locations")
    @WebResult(name = "get_resources_locations_response", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
    public GetResourcesLocationsResponseElement getResourcesLocations(
        @WebParam(name = "get_resources_locations", targetNamespace = "urn:toatech:ResourceManagement:1.0", partName = "params")
        GetResourcesLocationsElement params);

}
