
package oasis.names.tc.dss._1_0.core.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DssSignPortType", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    oasis.names.tc.saml._1_0.assertion.ObjectFactory.class,
    oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class
})
public interface DssSignPortType {


    /**
     * 
     * @param body
     * @return
     *     returns oasis.names.tc.dss._1_0.core.schema.SignResponse
     */
    @WebMethod(operationName = "Sign", action = "http://adss.intranet.gasnatural.com:8777/adss/signing/dss")
    @WebResult(name = "SignResponse", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema", partName = "body")
    public SignResponse sign(
        @WebParam(name = "SignRequest", targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema", partName = "body")
        SignRequest body);

}
