package momatools.webServices.trackorder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import momatools.webServices.common.IdentificationRequest;
import momatools.webServices.common.IdentificationResponse;
import momatools.webServices.message_types.CreateOrderRequest;
import momatools.webServices.message_types.CreateOrderResponse;
import momatools.webServices.message_types.GetDataOrderRequest;
import momatools.webServices.message_types.GetDataOrderResponse;
import momatools.webServices.message_types.UpdateCounterOrderRequest;
import momatools.webServices.message_types.UpdateCounterOrderResponse;
import momatools.webServices.message_types.UpdateOrderRequest;
import momatools.webServices.message_types.UpdateOrderResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "servicePortType", targetNamespace = "http://www.gasnaturalfenosa.com/MOMA/TrackOrder")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    momatools.webServices.common.ObjectFactory.class,
    momatools.webServices.message_types.ObjectFactory.class
})
public interface ServicePortTypeTrack {


    /**
     * 
     * @param identificationRequest
     * @param getDataOrderResponse
     * @param identificationResponse
     * @param getDataOrderRequest
     */
    @WebMethod(operationName = "get_data_order", action = "http://www.gasnaturalfenosa.com/MOMA/TrackOrder/get_data_order")
    public void getDataOrder(
        @WebParam(name = "IdentificationRequest", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, partName = "IdentificationRequest")
        IdentificationRequest identificationRequest,
        @WebParam(name = "GetDataOrderRequest", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", partName = "GetDataOrderRequest")
        GetDataOrderRequest getDataOrderRequest,
        @WebParam(name = "IdentificationResponse", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, mode = WebParam.Mode.OUT, partName = "IdentificationResponse")
        Holder<IdentificationResponse> identificationResponse,
        @WebParam(name = "GetDataOrderResponse", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", mode = WebParam.Mode.OUT, partName = "GetDataOrderResponse")
        Holder<GetDataOrderResponse> getDataOrderResponse);

    /**
     * 
     * @param identificationRequest
     * @param updateCounterOrderResponse
     * @param identificationResponse
     * @param updateCounterOrderRequest
     */
    @WebMethod(operationName = "update_counter_order", action = "http://www.gasnaturalfenosa.com/MOMA/TrackOrder/update_counter_order")
    public void updateCounterOrder(
        @WebParam(name = "IdentificationRequest", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, partName = "IdentificationRequest")
        IdentificationRequest identificationRequest,
        @WebParam(name = "UpdateCounterOrderRequest", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", partName = "UpdateCounterOrderRequest")
        UpdateCounterOrderRequest updateCounterOrderRequest,
        @WebParam(name = "IdentificationResponse", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, mode = WebParam.Mode.OUT, partName = "IdentificationResponse")
        Holder<IdentificationResponse> identificationResponse,
        @WebParam(name = "UpdateCounterOrderResponse", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", mode = WebParam.Mode.OUT, partName = "UpdateCounterOrderResponse")
        Holder<UpdateCounterOrderResponse> updateCounterOrderResponse);

    /**
     * 
     * @param identificationRequest
     * @param updateOrderResponse
     * @param identificationResponse
     * @param updateOrderRequest
     */
    @WebMethod(operationName = "update_order", action = "http://www.gasnaturalfenosa.com/MOMA/TrackOrder/update_order")
    public void updateOrder(
        @WebParam(name = "IdentificationRequest", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, partName = "IdentificationRequest")
        IdentificationRequest identificationRequest,
        @WebParam(name = "UpdateOrderRequest", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", partName = "UpdateOrderRequest")
        UpdateOrderRequest updateOrderRequest,
        @WebParam(name = "IdentificationResponse", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, mode = WebParam.Mode.OUT, partName = "IdentificationResponse")
        Holder<IdentificationResponse> identificationResponse,
        @WebParam(name = "UpdateOrderResponse", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", mode = WebParam.Mode.OUT, partName = "UpdateOrderResponse")
        Holder<UpdateOrderResponse> updateOrderResponse);

    /**
     * 
     * @param createOrderResponse
     * @param identificationRequest
     * @param createOrderRequest
     * @param identificationResponse
     */
    @WebMethod(operationName = "create_order", action = "http://www.gasnaturalfenosa.com/MOOMA/TrackOrder/create_order")
    public void createOrder(
        @WebParam(name = "IdentificationRequest", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, partName = "IdentificationRequest")
        IdentificationRequest identificationRequest,
        @WebParam(name = "CreateOrderRequest", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", partName = "CreateOrderRequest")
        CreateOrderRequest createOrderRequest,
        @WebParam(name = "IdentificationResponse", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, mode = WebParam.Mode.OUT, partName = "IdentificationResponse")
        Holder<IdentificationResponse> identificationResponse,
        @WebParam(name = "CreateOrderResponse", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", mode = WebParam.Mode.OUT, partName = "CreateOrderResponse")
        Holder<CreateOrderResponse> createOrderResponse);

}
