
package com.gasnaturalfenosa.moma.validationcsv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;

import com.gasnaturalfenosa.common.IdentificationRequest;
import com.gasnaturalfenosa.common.IdentificationResponse;
import com.gasnaturalfenosa.message_types.validatecsv.ValidateCSVRequest;
import com.gasnaturalfenosa.message_types.validatecsv.ValidateCSVResponse;





/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "servicePortType", targetNamespace = "http://www.gasnaturalfenosa.com/MOMA/ValidationCSV")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.gasnaturalfenosa.common.ObjectFactory.class,
    com.gasnaturalfenosa.message_types.validatecsv.ObjectFactory.class
})
public interface ServicePortType {


    /**
     * 
     * @param identificationRequest
     * @param validateCSVResponse
     * @param identificationResponse
     * @param validateCSVRequest
     */
    @WebMethod(action = "http://www.gasnaturalfenosa.com-soap/ValidationCSV/validateCSV")
    public void validateCSV(
        @WebParam(name = "IdentificationRequest", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, partName = "IdentificationRequest")
        IdentificationRequest identificationRequest,
        @WebParam(name = "ValidateCSVRequest", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", partName = "ValidateCSVRequest")
        ValidateCSVRequest validateCSVRequest,
        @WebParam(name = "IdentificationResponse", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, mode = WebParam.Mode.OUT, partName = "IdentificationResponse")
        Holder<IdentificationResponse> identificationResponse,
        @WebParam(name = "ValidateCSVResponse", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", mode = WebParam.Mode.OUT, partName = "ValidateCSVResponse")
        Holder<ValidateCSVResponse> validateCSVResponse);

}
