/**
 * ApiPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package activity.toa;

public interface ApiPortType extends java.rmi.Remote {
    public void create_activity(activity.toa.User user, java.lang.String date, java.lang.String resource_id, java.lang.String position_in_route, activity.toa.Property[] properties, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void update_activity(activity.toa.User user, java.lang.String activity_id, java.lang.String position_in_route, activity.toa.Property[] properties, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void reopen_activity(activity.toa.User user, java.lang.String activity_id, java.lang.String position_in_route, activity.toa.Property[] properties, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void start_activity(activity.toa.User user, java.lang.String activity_id, java.lang.String date, java.lang.String time, activity.toa.Property[] properties, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void complete_activity(activity.toa.User user, java.lang.String activity_id, java.lang.String date, java.lang.String time, activity.toa.Property[] properties, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void suspend_activity(activity.toa.User user, java.lang.String activity_id, java.lang.String date, java.lang.String time, activity.toa.Property[] properties, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void cancel_activity(activity.toa.User user, java.lang.String activity_id, java.lang.String date, java.lang.String time, activity.toa.Property[] properties, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void prework_activity(activity.toa.User user, java.lang.String activity_id, java.lang.String date, java.lang.String time, activity.toa.Property[] properties, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void delay_activity(activity.toa.User user, java.lang.String activity_id, java.lang.String date, int value, activity.toa.Property[] properties, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void get_activity(activity.toa.User user, java.lang.String activity_id, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void search_activities(activity.toa.User user, java.lang.String search_in, java.lang.String search_for, java.lang.String date_from, java.lang.String date_to, java.lang.String select_from, java.lang.String select_count, java.lang.String order, java.lang.String[] property_filter, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void get_route(activity.toa.User user, java.lang.String date, java.lang.String resource_id, java.lang.String[] property_filter, java.lang.Integer select_from, java.lang.Integer select_count, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.ActivityHolder activity, activity.toa.holders.Activity_listHolder activity_list) throws java.rmi.RemoteException;
    public void start_route(activity.toa.User user, java.lang.String resource_id, java.lang.String time, java.lang.String date, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg) throws java.rmi.RemoteException;
    public void end_route(activity.toa.User user, java.lang.String resource_id, java.lang.String time, java.lang.String date, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg) throws java.rmi.RemoteException;
    public void link_activities(activity.toa.User user, java.lang.String from_activity_id, java.lang.String to_activity_id, java.lang.String link_type, java.lang.String min_interval, java.lang.String max_interval, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg) throws java.rmi.RemoteException;
    public void unlink_activities(activity.toa.User user, java.lang.String from_activity_id, java.lang.String to_activity_id, java.lang.String link_type, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg) throws java.rmi.RemoteException;
    public void get_activity_links(activity.toa.User user, java.lang.String activity_id, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.LinkArrayHolder link) throws java.rmi.RemoteException;
    public void set_file(activity.toa.User user, java.lang.String entity_id, java.lang.String property_id, java.lang.String file_name, org.w3.www._2005._05.xmlmime.Base64Binary file_data, java.lang.String file_mime_type, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg) throws java.rmi.RemoteException;
    public void get_file(activity.toa.User user, java.lang.String entity_id, java.lang.String property_id, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, javax.xml.rpc.holders.StringHolder file_name, org.w3.www._2005._05.xmlmime.holders.Base64BinaryHolder file_data, javax.xml.rpc.holders.StringHolder file_mime_type) throws java.rmi.RemoteException;
    public void delete_file(activity.toa.User user, java.lang.String entity_id, java.lang.String property_id, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg) throws java.rmi.RemoteException;
    public void set_resource_preferences(activity.toa.User user, java.lang.String activity_id, activity.toa.Resource_preference[] preference, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg) throws java.rmi.RemoteException;
    public void get_resource_preferences(activity.toa.User user, java.lang.String activity_id, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.Resource_preferenceArrayHolder preference) throws java.rmi.RemoteException;
    public void set_required_inventories(activity.toa.User user, java.lang.String activity_id, activity.toa.Required_inventory[] required_inventory, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg) throws java.rmi.RemoteException;
    public void get_required_inventories(activity.toa.User user, java.lang.String activity_id, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.Required_inventoryArrayHolder required_inventory) throws java.rmi.RemoteException;
    public void get_activity_work_skills(activity.toa.User user, java.lang.String activity_id, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, activity.toa.holders.Work_skillArrayHolder work_skill, activity.toa.holders.Capacity_categoryArrayHolder capacity_category) throws java.rmi.RemoteException;
    public void get_activities(activity.toa.User user, activity.toa.Get_activities_resource_filter_element[] resources, activity.toa.Get_activities_date_filter date_range, java.lang.Integer select_from, int select_count, activity.toa.Get_activities_filter filter_expression, java.lang.String[] required_properties, javax.xml.rpc.holders.IntHolder result_code, javax.xml.rpc.holders.StringHolder error_msg, javax.xml.rpc.holders.StringHolder expression, activity.toa.holders.ActivitiesHolder activities, javax.xml.rpc.holders.BooleanWrapperHolder have_more_results, javax.xml.rpc.holders.StringHolder statistics) throws java.rmi.RemoteException;
}
