package momatools.webServices.activitypcc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import momatools.webServices.common.IdentificationRequest;
import momatools.webServices.common.IdentificationResponse;
import momatools.webServices.message_types.CreateActivityRequest;
import momatools.webServices.message_types.UpdateActivityRequest;
import momatools.webServices.message_types.UpdateActivityResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "servicePortType", targetNamespace = "http://www.gasnaturalfenosa.com/MOMA/ActivityPCC")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    momatools.webServices.common.ObjectFactory.class,
    momatools.webServices.message_types.ObjectFactory.class
})
public interface ServicePortType {


    /**
     * 
     * @param identificationRequest
     * @param createActivityRequest
     * @param createActivityResponse
     * @param identificationResponse
     */
    @WebMethod(operationName = "create_activity", action = "http://www.gasnaturalfenosa.com-soap/ActivityPCC/create_activity")
    public void createActivity(
        @WebParam(name = "IdentificationRequest", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, partName = "IdentificationRequest")
        IdentificationRequest identificationRequest,
        @WebParam(name = "CreateActivityRequest", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", partName = "CreateActivityRequest")
        CreateActivityRequest createActivityRequest,
        @WebParam(name = "IdentificationResponse", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, mode = WebParam.Mode.OUT, partName = "IdentificationResponse")
        Holder<IdentificationResponse> identificationResponse,
        @WebParam(name = "CreateActivityResponse", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", mode = WebParam.Mode.OUT, partName = "CreateActivityResponse")
        Holder<Object> createActivityResponse);

    /**
     * 
     * @param identificationRequest
     * @param updateActivityResponse
     * @param identificationResponse
     * @param updateActivityRequest
     */
    @WebMethod(operationName = "update_activity", action = "http://www.gasnaturalfenosa.com-soap/ActivityPCC/update_activity")
    public void updateActivity(
        @WebParam(name = "IdentificationRequest", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, partName = "IdentificationRequest")
        IdentificationRequest identificationRequest,
        @WebParam(name = "UpdateActivityRequest", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", partName = "UpdateActivityRequest")
        UpdateActivityRequest updateActivityRequest,
        @WebParam(name = "IdentificationResponse", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, mode = WebParam.Mode.OUT, partName = "IdentificationResponse")
        Holder<IdentificationResponse> identificationResponse,
        @WebParam(name = "UpdateActivityResponse", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", mode = WebParam.Mode.OUT, partName = "UpdateActivityResponse")
        Holder<UpdateActivityResponse> updateActivityResponse);

}
