
package gnf.moma.gendocumentfiles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;

import com.gasnaturalfenosa.message_types.gendocumentumfiles.GenDocumentumFilesRequest;
import com.gasnaturalfenosa.message_types.gendocumentumfiles.GenDocumentumFilesResponse;

import gnf.moma.gendocumentfiles.common.IdentificationRequest;
import gnf.moma.gendocumentfiles.common.IdentificationResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "servicePortType", targetNamespace = "http://www.gasnaturalfenosa.com/MOMA/GenDocumentumFiles")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	com.gasnaturalfenosa.message_types.gendocumentumfiles.ObjectFactory.class,
    gnf.moma.gendocumentfiles.common.ObjectFactory.class
})
public interface ServicePortType {


    /**
     * 
     * @param identificationRequest
     * @param genDocumentumFilesResponse
     * @param genDocumentumFilesRequest
     * @param identificationResponse
     */
    @WebMethod(operationName = "gen_documentumfiles", action = "http://www.gasnaturalfenosa.com-soap/GenDocumentumFiles/genDocFiles")
    public void genDocumentumfiles(
        @WebParam(name = "IdentificationRequest", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, partName = "IdentificationRequest")
        IdentificationRequest identificationRequest,
        @WebParam(name = "GenDocumentumFilesRequest", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", partName = "GenDocumentumFilesRequest")
        GenDocumentumFilesRequest genDocumentumFilesRequest,
        @WebParam(name = "IdentificationResponse", targetNamespace = "http://www.gasnaturalfenosa.com/common", header = true, mode = WebParam.Mode.OUT, partName = "IdentificationResponse")
        Holder<IdentificationResponse> identificationResponse,
        @WebParam(name = "GenDocumentumFilesResponse", targetNamespace = "http://www.gasnaturalfenosa.com/message-types", mode = WebParam.Mode.OUT, partName = "GenDocumentumFilesResponse")
        Holder<GenDocumentumFilesResponse> genDocumentumFilesResponse);

}
